# Description: Workflow that allow you to build and deploy java maven application using git flow. 
# Version 1.3.3
# GitHub Code: https://github.com/Iberia-Ent/software-engineering--java-maven-template
# GitHub Workflow: https://github.com/Iberia-Ent/software-engineering--workflow-java-maven
# Git Flow Code: https://github.com/Iberia-Ent/software-engineering--git-flow-template
name: CICD_JAVA_MAVEN

on:  
  push:  
    branches-ignore: [ main ]    
  pull_request:  
    branches: [  develop ]
    types:  [ opened, reopened, closed ]
  release:
    types:
      - created
            
jobs:    
  JAVA:
    uses: N512480/Test_Secret_key_Repo/tree/develop/.github/workflows/ci-cd-java-maven.yml@v1.6
    secrets:
        EMAIL_SECRET_PASSPHRASE: ${{ secrets.EMAIL_SECRET_PASSPHRASE }}
    name: Build project with Maven
    run: mvn -B package --file pom.xml